# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Create app directory
WORKDIR /app

# Copy package files
COPY package.json ./
COPY tsconfig.json ./

# Install dependencies without frozen lockfile
RUN pnpm install --no-frozen-lockfile --ignore-scripts

# Copy source files
COPY src ./src
COPY README.md ./

# Build the project
RUN pnpm run build

# Start the server
CMD ["node", "dist/index.js"]
